import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>StartUp Best Idea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>My StartUp</a>
        </h1>

        <p className={styles.description}>
          First things first!{' '}
          <code className={styles.code}>Hello World!</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Basic StartUp
        </a>
      </footer>
    </div>
  )
}

export default Home
